---
title: "Comparing number of bites and saliva titers of ZIKV- and DENV-infected Aedes albopictus, and estimate dose delivered to squirrel monkeys"
author: "Helene Cecilia"
format: html
---

```{r}
#| label: load-packages
#| include: false

rm(list=ls())

## Loading Packages  ------------------
library(ggplot2)
library(tidyverse)
library(BAS)
library(patchwork)
library(cowplot) # for draw_image
library(magick) # for draw_image
library(gghalves)
library(ggpubr)
library(car) # for leveneTest
library(MASS) # for glm.nb
library(VGAM) # for vglm
library(lme4) # for lmer
library(lmerTest)
library(modelr)
library(performance)
library(scales) # for trans_breaks, alpha function
library(broom) # for tidy
library(ggdist)
library(DHARMa)
library(effects)
library(glmmTMB)
library(data.table) # for %like%
library(multcomp) # for glht


## Set Work Directory ------------------------------------------------------
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # set to source file location
getwd()

## Global command
`%notin%` <- Negate(`%in%`)
```

```{r}
#| label : number-infectious-bites-day0
#| echo: false

denv_squirrel_total <- rep(15,10)
denv_squirrel_fed <- c(3,4,5,4,3,4,5,4,4,6)

# 14 mosquitoes instead of 15 in one case
zikv_squirrel_total <- c(15,15,15,14,15,15,15,15,15,15)
zikv_squirrel_fed <- c(9,5,10,11,4,6,7,4,7,9)

denv_cyno_total <- c(1,1,1,1,10,10,10,10,10)
denv_cyno_fed <- c(1,1,1,1,7,8,8,9,7)

zikv_cyno_total <- c(15,15,15)
zikv_cyno_fed <- c(7,11,7)

# positive mosquitoes after one passage in C6/36 cells
denv_squirrel_pos <- c(2,4,4,2,3,2,2,3,4,5)
zikv_squirrel_pos <- c(6,1,5,11,4,6,7,4,6,8)
denv_cyno_pos <- c(0,1,1,1,6,5,3,4,3) 
zikv_cyno_pos <- c(7,10,5)

denv_squirrel_fed_surv <- c(3,4,4,3,3,4,5,4,4,5) 
zikv_squirrel_fed_surv <- c(9,5,10,11,4,6,7,4,6,8) 
denv_cyno_fed_surv <- c(1,1,1,1,7,8,8,9,7) 
zikv_cyno_fed_surv <- c(7,11,7)

df <- data.frame(total = c(denv_squirrel_total,
                           denv_cyno_total,
                           zikv_squirrel_total,
                           zikv_cyno_total),
                 fed = c(denv_squirrel_fed,
                         denv_cyno_fed,
                         zikv_squirrel_fed,
                         zikv_cyno_fed),
                 fed_surv = c(denv_squirrel_fed_surv,
                              denv_cyno_fed_surv,
                              zikv_squirrel_fed_surv,
                              zikv_cyno_fed_surv),
                 pos = c(denv_squirrel_pos,
                         denv_cyno_pos,
                         zikv_squirrel_pos,
                         zikv_cyno_pos),
                 group = c(rep("Squirrel.Dengue virus",length(denv_squirrel_total)),
                           rep("Cyno.Dengue virus", length(denv_cyno_total)),
                           rep("Squirrel.Zika virus", length(zikv_squirrel_total)),
                           rep("Cyno.Zika virus", length(zikv_cyno_total))))

# exclude low exposure group of cynomolgus macaques
df_high <- df[df$total != 1,]

df_high$group <- gsub(" ","_",df_high$group) # no space for posthoc test to work
df_high$group <- as.factor(df_high$group)
df_high <- within(df_high, group <- relevel(group, ref = "Squirrel.Dengue_virus"))

# Raw number of infected bites in high exposure groups only
# apply positive proportion in (fed & survived) to (total fed)
# as an estimate of the true number of infectious bites received
df_high$prop_surv <- df_high$pos/df_high$fed_surv 
df_high$pos_corr <- round(df_high$prop_surv * df_high$fed)
# difference between observed and estimated number of positive bites
df_high$pos - df_high$pos_corr

df_high %>% group_by(group) %>% summarise(mean = mean(pos_corr),
                                          min = min(pos_corr),
                                          max = max(pos_corr))


# For this part we decided to remain purely descriptive but here's the code if you want to run proper tests ----
model <- glmmTMB(pos_corr ~ group,
                 family = poisson,
                 data = df_high)
simulateResiduals(model, plot = T)
# ok
testDispersion(model)
# ok
testZeroInflation(model)
# ok
MuMIn::AICc(model) # 124.3298

# m1 <- glmmTMB(pos_corr ~ group,
#                family = nbinom2,
#                data = df_high)
# # model convergence problem (tested nbinom1 and nbinom2)

plot(allEffects(model, partial.residuals = T))
summary(model)

# select only the biologically relevant comparisons
tuk = glht(model, linfct = mcp(group = c("Cyno.Dengue_virus - Squirrel.Dengue_virus = 0",
                                          "Cyno.Zika_virus - Squirrel.Zika_virus = 0",
                                          "Squirrel.Dengue_virus - Squirrel.Zika_virus = 0",
                                          "Cyno.Dengue_virus - Cyno.Zika_virus = 0"))) 
summary(tuk, test = adjusted("none"))
summary(tuk, test = adjusted("fdr")) # benjamini-hochberg (false discovery rate) correction

ggplot(df_high) + geom_jitter(aes(x = group, y = pos_corr)) +
  geom_boxplot(aes(x = group, y = pos_corr),
               fill = NA)

# Mean proba (response scale) and CI for each group
new_dat <- data.frame(group = c("Squirrel.Dengue_virus",
                                "Cyno.Dengue_virus",
                                "Squirrel.Zika_virus",
                                "Cyno.Zika_virus"))
pp <- predict(model, se.fit = TRUE, newdata = new_dat)
# the inverse link of a poisson is exp
ci_lwr <- with(pp, exp(fit + qnorm(0.025)*se.fit))
ci_upr <- with(pp, exp(fit + qnorm(0.975)*se.fit))
means <- with(pp, exp(fit))
names(means) <- new_dat$group
names(ci_upr) <- new_dat$group
names(ci_lwr) <- new_dat$group
means
ci_lwr
ci_upr

```

```{r}
#| label: positive-saliva-titers
#| echo: false

# Saliva titers of mosquitoes infecting NHP ----
# using titers rounded as integers 

# For the first 3 exp (all except ZIKV cyno)
# for those positive only after passage, we put 39 for now (LOD - 1)
# For ZIKV cyno
# one positive only after passage, keep LOD/2 = 5

denv_sq_titer <- c(c(39,39,0), # id 6314
                c(40,39,39,39), # id 6519
                c(40,838,679,39), # id 4516
                c(1836,39,0), # id 5045
                c(40,39,39,0), # id 4872
                c(40,39,0,0), # id 6401
                c(39,39,0,0,0), # id 6363
                c(120,80,39,0), # id 6552
                c(160,40,39,39), # id 6242 : titer = 40 was negative post passage
                c(40,40,40,80,39)) # id 5910

denv_cy_titer <- c(c(39), # id SB393, negative even after passage but initiated a PRNT response
                     c(39), # id FR469A
                     c(39), # id BC407
                     c(39), # id CP60
                     c(39,39,39,39,39,39,0), # id BC116A
                     c(39,39,39,39,39,0,0,0), # id FR423A
                     c(39,39,39,0,0,0,0,0), # id SB395
                     c(39,39,39,39,0,0,0,0,0), # id FR840
                     c(39,39,39,0,0,0,0)) # id BC167

zikv_sq_titer <- c(c(160,639,279,1238,1158,39,0,0,0), # id 6550
                c(639,0,0,0,0), # id 6518
                c(2076,1078,1557,39,39,0,0,0,0,0), # id 6311
                c(918,639,639,240,120,80,40,240,3990,679,39), # id 5013
                c(479,240,80,39), # id 4806
                c(279,758,40,359,40,40), # id 6347
                c(1158,3990,878,439,3990,3990,1477), # id 6359
                c(719,519,39,39), # id 5730
                c(1437,120,479,878,160,39), # id 4683
                c(918,2275,798,838,2275,40,1277,39)) # id 4728

# for ZIKV cyno, the LOD was 10 so 5 for those positive after passage only
# 0 not included here
zikv_cy_titer <- c(c(60,1500,460,1300,10300,9200,3100), # UGZ626
                   c(5,30,70,160,10,1500,4600,70,21000,2600), # EC944
                   c(2600,370,22000,210,830)) # FR1221

df <- data.frame(titer = c(denv_sq_titer, denv_cy_titer,
                           zikv_sq_titer, zikv_cy_titer),
                 virus = c(rep("Dengue virus",length(denv_sq_titer)),
                           rep("Dengue virus",length(denv_cy_titer)),
                           rep("Zika virus", length(zikv_sq_titer)),
                           rep("Zika virus", length(zikv_cy_titer))),
                 NHP = c(rep("Squirrel",length(denv_sq_titer)),
                         rep("Cyno",length(denv_cy_titer)),
                         rep("Squirrel", length(zikv_sq_titer)),
                         rep("Cyno", length(zikv_cy_titer))),
                 ID = c(c(rep(6314,3),
                        rep(6519,4),
                        rep(4516,4),
                        rep(5045,3),
                        rep(4872,4),
                        rep(6401,4),
                        rep(6363,5),
                        rep(6552,4),
                        rep(6242,4),
                        rep(5910,5)),c(rep("SB393",1),
                                       rep("FR469A",1),
                                       rep("BC407",1),
                                       rep("CP60",1),
                                       rep("BC116A",7),
                                       rep("FR423A",8),
                                       rep("SB395",8),
                                       rep("FR840",9),
                                       rep("BC167",7)),c(rep(6550,9),
                                                         rep(6518,5),
                                                         rep(6311,10),
                                                         rep(5013,11),
                                                         rep(4806,4),
                                                         rep(6347,6),
                                                         rep(6359,7),
                                                         rep(5730,4),
                                                         rep(4683,6),
                                                         rep(4728,8)),
                                                                    c(rep("UGZ626",7),
                                                                       rep("EC944",10),
                                                                       rep("FR1221",5))))

# For all except ZIKV cyno : 
# Assign titers positive only after passage a value of half LOD : 20 
# we also tried sampling random values between 1 and 39 (for Levene's test)
# it improved model residuals but didn't change the conclusions
df_fixLOD <- df
df_fixLOD$titer[df_fixLOD$titer == 39] <- 20

# Exclude the zeros
df_fixLOD <- df_fixLOD[df_fixLOD$titer != 0,]
log10(mean(df_fixLOD$titer))

df_fixLOD$log_titer <- log10(df_fixLOD$titer) 
df_fixLOD$group <- interaction(df_fixLOD$NHP,df_fixLOD$virus)

df_fixLOD$virus <- as.factor(df_fixLOD$virus)
df_fixLOD <- within(df_fixLOD, virus <- relevel(virus, ref = "Dengue virus"))

# Figure for a conference
# p <- ggplot(df_fixLOD, aes(x = virus, y = log_titer)) +
#   geom_boxplot(outlier.shape = NA) + 
#   geom_jitter(aes(fill = virus,
#                   color = virus,
#                   shape = virus),
#               size = 7,
#               alpha = 0.7,
#               width = 0.3) +
#   scale_fill_manual(values = c("Dengue virus" = "#1c812b",
#                                 "Zika virus" = "#253dbe")) +
#   scale_color_manual(values = c("Dengue virus" = "#1c812b",
#                                 "Zika virus" = "#253dbe")) +
#   scale_shape_manual(values = c("Dengue virus" = 21,
#                                 "Zika virus" = 22)) +
#   labs(y = bquote("Mosquito saliva titer ("*log[10]~"PFU/ml)"),
#        x = "",
#        fill = "Mosquito status",
#        color = "Mosquito status",
#        shape = "Mosquito status") +
#   guides(fill = guide_legend(override.aes = list(alpha = 1))) +
#     theme_cowplot() +
#   # theme_classic() +
#   theme(axis.text.x = element_blank(),
#         axis.text.y = element_text(size = 30),
#         axis.title.y = element_text(size = 38,
#                                     margin = margin(r = 20)),
#         legend.position = c(0.95,0.27),
#         plot.margin = unit(c(0,7.5,0,0.35), "cm"),
#         legend.text = element_text(size = 38),
#         legend.title = element_text(size = 38))
# 
# img_mosq <- magick::image_read("~/Documents/POSTDOC/Presentations/Images/mosquito_outline.png")
# 
# p_draw <- ggdraw() + 
#   draw_plot(p) +
#   draw_image(image = img_mosq, 
#              x = 0.1, y = 0.8, scale = 0.15,
#              valign = 0, halign = 0)
# 
# png(filename = here("output","TropMed23","saliva_titer_per_virus.png"),
#     width = 1600, height = 750)
# print(p_draw)
# dev.off()

# the variability for DENV is probably underestimated because we put the same value (LOD/2) for all < LOD
# but changing to a random value between 0 and LOD is also artificial, although it is more conservative : it likely overestimates the variability, so if it still detects lower variability in the DENV group, it's likely true
# only one value for ZIKV cyno so half LOD (5) is fine
df_randomLOD <- df
n_draw <- length(df_randomLOD$titer[df_randomLOD$titer == 39])
df_randomLOD$titer[df_randomLOD$titer == 39]<- runif(n_draw,1,39)
df_randomLOD$log_titer <- log10(df_randomLOD$titer)
df_randomLOD <- df_randomLOD[df_randomLOD$titer != 0,]

hist(df_randomLOD$log_titer)
shapiro.test(df_randomLOD$log_titer) # not normal but should be fine for Levene
ggplot(df_randomLOD, aes(x = virus, y = log_titer)) +
  geom_boxplot(outlier.shape = NA) + geom_jitter(aes(color = virus))
summary(as.factor(df_randomLOD$virus)) # unbalanced but should be fine for Levene

# all signif
leveneTest(titer ~ virus, data = df_randomLOD)
leveneTest(log_titer ~ virus, data = df_randomLOD)

# Model - fixed LOD ----
m0 <- glmmTMB(log_titer ~ virus, data = df_fixLOD)

simulateResiduals(m0, plot = T) 
# issues
plotResiduals(m0, form = model.frame(m0)$virus) 
testDispersion(m0) 
# not signif

m1 <- glmmTMB(log_titer ~ virus,
              data = df_fixLOD,
              dispformula = ~ virus)

simulateResiduals(m1, plot = T) 
# still issues 

anova(m0,m1) # m1 prefered (dispersion term significant, see summary)

summary(m1)

# Model - random LOD (to be consistent with variance analysis) ----
m2 <- glmmTMB(log_titer ~ virus, data = df_randomLOD)

simulateResiduals(m2, plot = T) 
# issues
plotResiduals(m2, form = model.frame(m2)$virus) 
testDispersion(m2) 
# not signif

m3 <- glmmTMB(log_titer ~ virus,
              data = df_randomLOD,
              dispformula = ~ virus)

simulateResiduals(m3, plot = T) 
# no issues 

anova(m2,m3) # m3 prefered 

summary(m3)

# Mean proba (response scale) and CI for each group
new_dat <- data.frame(virus = c("Dengue virus","Zika virus"))
pp <- predict(m3, se.fit = TRUE, newdata = new_dat)
ci_lwr <- with(pp, fit + qnorm(0.025)*se.fit)
ci_upr <- with(pp, fit + qnorm(0.975)*se.fit)
means <- with(pp, fit)
names(means) <- new_dat$virus
names(ci_upr) <- new_dat$virus
names(ci_lwr) <- new_dat$virus
means
ci_lwr
ci_upr

```

```{r}
#| label: dose-delivered
#| echo: false

denv_sq_titer <- c(c(39,39,0), # id 6314
                c(40,39,39,39), # id 6519
                c(40,838,679,39), # id 4516
                c(1836,39,0), # id 5045
                c(40,39,39,0), # id 4872
                c(40,39,0,0), # id 6401
                c(39,39,0,0,0), # id 6363
                c(120,80,39,0), # id 6552
                c(160,40,39,39), # id 6242 : titer = 40 was negative post passage
                c(40,40,40,80,39)) # id 5910

denv_cy_titer <- c(c(39), # id SB393, negative even after passage but initiated a PRNT response
                     c(39), # id FR469A
                     c(39), # id BC407
                     c(39), # id CP60
                     c(39,39,39,39,39,39,0), # id BC116A
                     c(39,39,39,39,39,0,0,0), # id FR423A
                     c(39,39,39,0,0,0,0,0), # id SB395
                     c(39,39,39,39,0,0,0,0,0), # id FR840
                     c(39,39,39,0,0,0,0)) # id BC167

zikv_sq_titer <- c(c(160,639,279,1238,1158,39,0,0,0), # id 6550
                c(639,0,0,0,0), # id 6518
                c(2076,1078,1557,39,39,0,0,0,0,0), # id 6311
                c(918,639,639,240,120,80,40,240,3990,679,39), # id 5013
                c(479,240,80,39), # id 4806
                c(279,758,40,359,40,40), # id 6347
                c(1158,3990,878,439,3990,3990,1477), # id 6359
                c(719,519,39,39), # id 5730
                c(1437,120,479,878,160,39), # id 4683
                c(918,2275,798,838,2275,40,1277,39)) # id 4728

# for ZIKV cyno, the LOD was 10 so 5 for those positive after passage only
# 0 not included here
zikv_cy_titer <- c(c(60,1500,460,1300,10300,9200,3100), # UGZ626
                   c(5,30,70,160,10,1500,4600,70,21000,2600), # EC944
                   c(2600,370,22000,210,830)) # FR1221

df <- data.frame(titer = c(denv_sq_titer, denv_cy_titer,
                           zikv_sq_titer, zikv_cy_titer),
                 virus = c(rep("Dengue virus",length(denv_sq_titer)),
                           rep("Dengue virus",length(denv_cy_titer)),
                           rep("Zika virus", length(zikv_sq_titer)),
                           rep("Zika virus", length(zikv_cy_titer))),
                 NHP = c(rep("Squirrel",length(denv_sq_titer)),
                         rep("Cyno",length(denv_cy_titer)),
                         rep("Squirrel", length(zikv_sq_titer)),
                         rep("Cyno", length(zikv_cy_titer))),
                 ID = c(c(rep(6314,3),
                        rep(6519,4),
                        rep(4516,4),
                        rep(5045,3),
                        rep(4872,4),
                        rep(6401,4),
                        rep(6363,5),
                        rep(6552,4),
                        rep(6242,4),
                        rep(5910,5)),c(rep("SB393",1),
                                       rep("FR469A",1),
                                       rep("BC407",1),
                                       rep("CP60",1),
                                       rep("BC116A",7),
                                       rep("FR423A",8),
                                       rep("SB395",8),
                                       rep("FR840",9),
                                       rep("BC167",7)),c(rep(6550,9),
                                                         rep(6518,5),
                                                         rep(6311,10),
                                                         rep(5013,11),
                                                         rep(4806,4),
                                                         rep(6347,6),
                                                         rep(6359,7),
                                                         rep(5730,4),
                                                         rep(4683,6),
                                                         rep(4728,8)),
                                                                    c(rep("UGZ626",7),
                                                                       rep("EC944",10),
                                                                       rep("FR1221",5))))


# Assign titers positive only after passage a value of half LOD : 20 
# not showed : we also tried sampling random values between 1 and 39
# it improved model residuals but didn't change the conclusions
df_fixLOD <- df
df_fixLOD$titer[df_fixLOD$titer == 39] <- 20

# sum titers per monkey
dose_fixLOD <- df_fixLOD %>% group_by(ID) %>% mutate(dose = sum(titer)) %>% ungroup()

dose_fixLOD <- unique(dose_fixLOD[,c("ID","NHP","virus","dose")])
dose_fixLOD$log_dose <- log10(dose_fixLOD$dose) # +1 is no longer necessary
dose_fixLOD$virus <- as.factor(dose_fixLOD$virus)

# Distinguish exposure groups
dose_fixLOD$treatment <- "15Mosq"
dose_fixLOD[dose_fixLOD$ID %in% c("SB393","FR469A","BC407","CP60"),]$treatment <- "1Mosq"
dose_fixLOD[dose_fixLOD$ID %in% c("BC116A","FR423A","SB395","FR840","BC167"),]$treatment <- "10Mosq"

dose_fixLOD$group <- interaction(dose_fixLOD$NHP,dose_fixLOD$treatment,dose_fixLOD$virus)
dose_fixLOD$group <- gsub(" ","_",dose_fixLOD$group) # no space for posthoc test to work
dose_fixLOD$group <- as.factor(dose_fixLOD$group)
dose_fixLOD <- within(dose_fixLOD, group <- relevel(group, ref = "Squirrel.15Mosq.Dengue_virus"))

dose_fixLOD %>% group_by(group) %>% summarise(mean = log10(mean(10**log_dose)),
                                          min = min(log_dose),
                                          max = max(log_dose))

# For this part we decided to remain purely descriptive but here's the code if you want to run proper tests ----
# Model
model <- glmmTMB(log_dose ~ group,
                 data = dose_fixLOD)
simulateResiduals(model, plot = T)
# ok 
testDispersion(model)
# ok
plot(allEffects(model, partial.residuals = T))
summary(model)

# select only the biologically relevant comparisons
tuk = glht(model, linfct = mcp(group = c("Cyno.10Mosq.Dengue_virus - Squirrel.15Mosq.Dengue_virus = 0",
                                         "Cyno.10Mosq.Dengue_virus - Cyno.1Mosq.Dengue_virus = 0",
                                          "Cyno.15Mosq.Zika_virus - Squirrel.15Mosq.Zika_virus = 0",
                                          "Squirrel.15Mosq.Dengue_virus - Squirrel.15Mosq.Zika_virus = 0",
                                          "Cyno.10Mosq.Dengue_virus - Cyno.15Mosq.Zika_virus = 0"))) 
summary(tuk, test = adjusted("none"))
summary(tuk, test = adjusted("fdr")) # benjamini-hochberg (false discovery rate) correction

ggplot(dose_fixLOD) + geom_jitter(aes(x = group, y = log_dose)) +
  geom_boxplot(aes(x = group, y = log_dose),
               fill = NA)

# Mean proba (response scale) and CI for each group
new_dat <- data.frame(group = c("Squirrel.15Mosq.Dengue_virus",
                                "Cyno.10Mosq.Dengue_virus",
                                "Cyno.1Mosq.Dengue_virus",
                                "Squirrel.15Mosq.Zika_virus",
                                "Cyno.15Mosq.Zika_virus"))
pp <- predict(model, se.fit = TRUE, newdata = new_dat)
ci_lwr <- with(pp, fit + qnorm(0.025)*se.fit)
ci_upr <- with(pp, fit + qnorm(0.975)*se.fit)
means <- with(pp, fit)
names(means) <- new_dat$group
names(ci_upr) <- new_dat$group
names(ci_lwr) <- new_dat$group
means
ci_lwr
ci_upr

```
